### PR TITLE
Remove object check in parse value

### PR DESCRIPTION
**Pull request by vlkous**
If I set only string don't throw the check end return stringify string

example:

```
dispatch(localStorage.setItem('foo', 'bar')).then(
  dispatch(localStorage.getItem('foo')).then(item => {
    console.log(item) // "bar"
  })
)
```

### CODE REVIEW

**Comment by ashaffer** [comment]
Hmm...I wonder if we should be parsing values at all? What do you think?

**Comment by vlkous** [comment]
Yes, I think. If you all stringify. You need to parse all back.

And best will be try ... catch stringify to

**Comment by ashaffer** [comment]
Ah, I see what you're saying. Ok, merging.

**Comment by ashaffer** [comment]
Bumped & published.

**Pull request merged**
